### ISSUE TITLE
DSL Error with Cocoapods 1.0.0.beta.4

### ISSUE THREAD

**Issue by bclymer** [ashleymills/Reachability.swift#89]
Podfile (simplified a bit)
```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
```
I receive
```
[!] Unable to find a specification for 'ReachabilitySwift'.

[!] Unable to load a podspec from `ReachabilitySwift.podspec`, skipping:

Pod::DSLError
```
I *just* upgraded to 1.0.0.beta.4, and everything was working for in 0.39.0, so I guess their required format changed?

**Comment by felipeplets** [comment]
Same thing here. 
@bclymer do you found the issue or any workaround?

**Comment by bclymer** [comment]
@felipeplets I ended up just including `Reachability.swift` in my project directly, and no longer using the pod.

I will likely go back to using the pod once this is fixed though, just for the automatic updates.

**Comment by jyoung84** [comment]
Same, I'm guessing the podspec DSL changed since it was written for this project.

**Comment by ddengler** [comment]
same here with beta 5

**Comment by YayConnolly** [comment]
Still an issue for `1.0.0.beta.6`.

I tried running `pod spec create "https://github.com/ashleymills/Reachability.swift"` because passing a github url is supposed to pre-populate the generated podspec, but got:
```
[!] Unable to fetch data for `ashleymills/Reachability`

[!] Request to https://api.github.com/repos/ashleymills/Reachability failed - 404

[!] Not Found
```

Same exact message when I tried with `pod spec create https://github.com/ashleymills/Reachability.swift/tree/cf126c0584a209143c75bf1d0f23fd904891e26e`. 

So apparently the ".swift" at the end of this repo name is being dropped with that command, not sure if it's related.

Attached is the blank .podspec file that you get when running `pod spec create example` with version 1.0.0.beta.6 (appended ".txt" so I could upload it here).
[example.podspec.txt](https://github.com/ashleymills/Reachability.swift/files/180597/example.podspec.txt)

**Comment by Souf-R** [comment]
Same error here, using: `CocoaPods 1.0.0.beta.6` with `XCode 7.3`

```
Analyzing dependencies
Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift`
[!] Unable to find a specification for 'ReachabilitySwift'.

[!] Unable to load a podspec from `ReachabilitySwift.podspec`, skipping:

Pod::DSLError
```

**Comment by askielboe** [comment]
Same issue here with `CocoaPods 1.0.0.beta.6` | `ruby 2.0.0p648` | `XCode 7.3`

Running `pod spec lint ReachabilitySwift.podspec` yields:

     -> ReachabilitySwift.podspec
        - ERROR | spec: The specification defined in `ReachabilitySwift.podspec` could not be loaded.


    [!] Invalid `ReachabilitySwift.podspec` file: undefined method `platform=' for #    <Pod::Specification::DSL::PlatformProxy:0x007ffaa40e9560>.

     #  from ReachabilitySwift.podspec:12
     #  -------------------------------------------
     #  # Source Info
     >    s.ios.platform = :ios, "9.2"
     #    s.osx.platform = :osx, "10.11"
     #  -------------------------------------------


    Analyzed 1 podspec.

    [!] The spec did not pass validation, due to 1 error.

**Comment by felipeplets** [comment]
Same issue with `CocoaPods 1.0.0.beta.7` | `Ruby 2.0.0p648` | `Xcode 7.3`

**Comment by evermeer** [comment]
I downgraded to cocoapods 0.39 and I still get the same error

**Comment by mathiasquintero** [comment]
I still get this problem! Any way around it without including Reachability into the project directly?

**Comment by hw-credeo** [comment]
pod 'ReachabilitySwift'

Works with 1.0.0

**Comment by ashleymills** [comment]
Now works with Cocoapods 1.0
