### ISSUE TITLE
from Objective-c class - use of undeclared identifier 'Reachability'

### ISSUE THREAD

**Issue by mime29** [ashleymills/Reachability.swift#141]
Before version 3 I could use Reachibility class within objc code.

now, I get this error.
I install with Cocoapods 1.0.1, 
use 

`@import ReachabilitySwift;
`
in my .m file but it fails to compile.

**Comment by ashleymills** [comment]
Have you tried using the 2.4 version?

**Comment by ashleymills** [comment]
I don't have any active apps containing objc so haven't tried including Reachability.swift in an objc file. If you can't import it, it would seem to indicate that Reachability.swift didn't build correctly.

**Comment by mime29** [comment]
2.4 is compatible with Swift 3 ?

**Comment by ashleymills** [comment]
Ah, right,  I see - you've got a combined Swift 3 / objc project. Version 2.4 is Swift 2.3 (confusingly)

**Comment by mime29** [comment]
Additional note: It was working with 2.4
I just updated to the v 3 today and it doesn't work anymore.
Maybe there is a use of the Public keyword instead of Open  for the class itself? - just an idea -

**Comment by ashleymills** [comment]
Interesting. According to the release notes… 
> Classes declared as public can no longer be subclassed outside of their defining module, and methods declared as public can no longer be overridden outside of their defining module. To allow a class to be externally subclassed or a method to be externally overridden, declare them as open, which is a new access level beyond public.
… which doesn't sound as though it would affect importing into objective c

**Comment by mime29** [comment]
Really??
What I pasted earlier was from Apple's interoperability Guide.
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122

Let me try to change it to Open ...

**Comment by mime29** [comment]
Do you need me to make a pullRequest? The only issue is I can't keep the init?() in that case apparently. If you know a way to keep it optional AND compatible with obj-c that could be nice.

**Comment by mime29** [comment]
I m currently using this updated version of the library in my project.
Please update master with this pull request if you think it's fine.
I use Reachability in objc and swift, works fine on both sides.
Thank you.

https://github.com/ashleymills/Reachability.swift/pull/152

**Comment by ashleymills** [comment]
Supporting dual objc / swift projects is a non-goal for this library
